// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           20
// Async Callback (empty):               1
// Total number of exported functions:  22

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    subscription_fee
    (
        init => init
        addAcceptedFeesTokens => add_accepted_fees_tokens
        setMinDepositValue => set_min_deposit_value
        deposit => deposit
        withdrawFunds => withdraw_funds
        getAcceptedFeesTokens => accepted_fees_tokens
        getUserDepositedFees => user_deposited_fees
        getMinStableTokenDepositValue => min_stable_token_deposit_value
        getPendingServices => pending_services
        getServiceInfo => service_info
        getSubscribedUsers => subscribed_users
        registerService => register_service
        addExtraServices => add_extra_services
        unregisterService => unregister_service
        unregisterServiceByOwner => unregister_service_by_owner
        approveService => approve_service
        subscribe => subscribe
        unsubscribe => unsubscribe
        subtractPayment => subtract_payment
        addPairAddress => add_pair_address
        removePairAddress => remove_pair_address
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
