// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           23
// Async Callback (empty):               1
// Total number of exported functions:  25

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    subscription_fee
    (
        init => init
        addAcceptedFeesTokens => add_accepted_fees_tokens
        setMaxUserDeposits => set_max_user_deposits
        deposit => deposit
        withdrawFunds => withdraw_funds
        getAcceptedFeesTokens => accepted_fees_tokens
        getUserDepositedFees => user_deposited_fees
        getMaxUserDeposits => max_user_deposits
        getMinUserDepositValue => min_user_deposit_value
        getPendingServices => pending_services
        getMaxPendingServices => max_pending_services
        getServiceInfo => service_info
        getSubscribedUsers => subscribed_users
        setMaxServiceInfoNo => set_max_service_info_no
        setMaxPendingServices => set_max_pending_services
        registerService => register_service
        unregisterService => unregister_service
        unregisterServiceByOwner => unregister_service_by_owner
        approveService => approve_service
        subscribe => subscribe
        unsubscribe => unsubscribe
        subtractPayment => subtract_payment
        addUsdcPair => add_pair_address
        removeUsdcPair => remove_pair_data
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
