[package]
name = "farm-boosted-rewards-subscriber-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = ["you"]

[dev-dependencies]

[dependencies.farm-boosted-rewards-subscriber]
path = ".."

[dependencies.multiversx-sc-meta]
version = "=0.45.1"
default-features = false
