// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           19
// Async Callback (empty):               1
// Total number of exported functions:  21

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    farm_boosted_rewards_subscriber
    (
        init => init
        upgrade => upgrade
        getSimpleLockAddress => simple_lock_address
        getLockPeriod => lock_period
        getNormalUserPercentage => normal_user_percentage
        getPremiumUserPercentage => premium_user_percentage
        getTotalFees => total_fees
        getEnergyThreshold => energy_threshold
        addFarm => add_farm
        removeFarm => remove_farm
        performClaimRewardsOperations => perform_claim_rewards_operations_endpoint
        subtractPayment => subtract_payment_endpoint
        claimFees => claim_fees
        performMexOperations => perform_mex_operations_endpoint
        registerService => register_service
        unregisterService => unregister_service
        getFeesContractAddress => fees_contract_address
        getUserFees => user_fees
        setEnergyFactoryAddress => set_energy_factory_address
        getEnergyFactoryAddress => energy_factory_address
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
